### PR TITLE
DROOLS-2644: Update screenshots of the drools workbench

### PR DESCRIPTION
**Pull request by jomarko**
Updated the screenshots to show basic scenario of creating rules using guided decision tables.

Removed screenshots of obsolete  editors to make the landing page more appealing.

### CODE REVIEW

**Comment by jomarko** [comment]
@etirelli would you mind to have a look?

**Comment by etirelli** [comment]
Looks good @jomarko , thanks!

**Comment by jomarko** [comment]
@mbiarnes @manstis would you mind to merge please?

**Comment by manstis** [comment]
@mbiarnes Whilst I can, and have, merged this PR IDK if there are other steps needed to _publish_ them.

**Comment by jomarko** [comment]
@manstis I don't know the process of publishing neither, but if you check drools.org, the screenshots are updated, so one more time, thanks for merge.

**Pull request merged**
