### PR TITLE
DROOLS-2602: added individual deployables

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/drools-website/pull/102
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1017

**Comment by mareknovotny** [comment]
@mbiarnes one thing which makes me a little bit hesitant to merge this is the real purpose of these links. see my question to the jira reporter https://issues.jboss.org/browse/DROOLS-2602?focusedCommentId=13765642&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13765642

**Comment by mbiarnes** [comment]
@mareknovotny when you download the *zip from web site and you unzip it you have also the wars
 @etirelli should decide if this change is wanted.
It was not to much time invested to have these wars. But when we decide to have them both PRs have to be merged - otherwise closed.

**Comment by mareknovotny** [comment]
@mbiarnes yes, I know, but the reporter specifically asked for

> So I need just kie-server-7.7.0.Final-webc.war

**Comment by mbiarnes** [comment]
@mareknovotny then it was my "overmotivated" view in the future - what is, if another user wants the ee7 ? Does it make sense to have only this one?

**Comment by mareknovotny** [comment]
@mbiarnes I am not against publishing and adding this into web downloads links, Just it seemed to me that using Maven repository is more straightforward for anybody and you could actually point in download links directly to those Maven artifacts too https://repo1.maven.org/maven2/org/kie/server/kie-server/7.24.0.Final/ , so you don't need to upload them to our download area additionally as you have there zips already.

**Comment by mbiarnes** [comment]
@mareknovotny sounds good!

**Comment by mbiarnes** [comment]
@mareknovotny now we can close https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1017/files - the ee7,ee8 and webc WAR link links to https://repo1.maven.org/maven2/org/kie/server/kie-server/7.24.0.Final/

**Pull request merged**
