### PR TITLE
DROOLS-7113 When Drools 8 published, update links on website

### PR DESCRIPTION
**Pull request by tarilabs**
https://issues.redhat.com/browse/DROOLS-7113

Raising as draft PR, so when artifacts are published and available, we just need to update in `pom.yaml`,
from: `8.28.0.Beta`
to: `8.29.0.Final`

Some preview of highlighted changes (if you notice anything unrelated to DROOLS-7113, please track it as separate JIRA):

image

image

image

image

### CODE REVIEW

**Review by tkobayas — APPROVED** [review]
Thank you, @tarilabs  !

One minor comment: This link says "HTML Single" but it's an antora website. For example, OptaPlanner site says "documentation website" (https://www.optaplanner.org/learn/documentation.html). Do you want to change the word?

doc-link2

**Comment by tarilabs** [comment]
> One minor comment: This link says "HTML Single" but it's an antora website. For example, OptaPlanner site says "documentation website" (https://www.optaplanner.org/learn/documentation.html). Do you want to change the word?

thank you for the well spotted, I believe is worthy to try give it a different designation

image

so I have replaced it with "Drools documentation and User Guide" in 2b8aee4 for now, we can always change it later again :)

**Review by mbiarnes — APPROVED** [review]
LGTM

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
@tarilabs @tkobayas I think we are good with that one right ?

**Comment by tarilabs** [comment]
@radtriste waiting for blog post to be effectively published before merging this one.

**Review by mariofusco — APPROVED** [review]

**Pull request merged**
